### ISSUE TITLE
Migration distances not in KM with a lat/long dataset

### ISSUE THREAD

**Issue by jmerkle1** [jmerkle1/Migration-Mapper#18]
When a dataset is in lat/long, the migration distances calculated in app 4 (i.e., the CalcSeqDistances.R function) are not calculated in KM, they are in decimal degrees. Need to add a line in CalcSeqDistances.R function to note if the sequences are in lat/long, and if so, transform into UTM before calculating the distances.

**Comment by gagecarto** [comment]
Hey @jmerkle1 - I am looking into this now. When sequences are written as RDS files, they're always converted to 4326 firstbefore being saved. I think we could solve this by converting to the UTM before writing files. 

I am not sure why I chose to write to 4326 before saving. Do you see any downstream issues with the RDS sequences if they're in UTM instead of decimal degrees?

https://github.com/jmerkle1/Migration-Mapper/blob/dc32cf3618c079057d067783cf9c8bbf3592dcb5/app3_sequenceWriting/scripts/app3_calcSequences.R#L68

**Comment by gagecarto** [comment]
It probably makes sense to convert the RDS sequences to UTM. The sequence RDS files are used to calculate distances but are also fed into the cluster when calculating UDs. I just want to make sure it won't cause issues when we're calculating UDs

**Comment by gagecarto** [comment]
Sequences are now calculated in UTM. You can pull down a new copy and see. I can now see reasonable values in the ...migration_distance_info.csv files.
